#!/usr/bin/env python3
 
from http.server import BaseHTTPRequestHandler, HTTPServer
import setproctitle
import os
 
class HTTPServer_RequestHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        self.send_response(200)
        message = self.client_address[0] + "\n"
        self.wfile.write(bytes(message, "utf8"))
        return

    def run(port = 80):
        server_address = ('', port)
        httpd = HTTPServer(server_address, HTTPServer_RequestHandler)
        httpd.serve_forever()

def main():
    setproctitle.setproctitle(os.path.basename(__file__))
    HTTPServer_RequestHandler.run(8080)

if __name__ == "__main__":
    main()
